# docker-compose development config (placeholder)
version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: bibliflow_db
      POSTGRES_USER: bibliflow
      POSTGRES_PASSWORD: bibliflow
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    volumes:
      - redis_data:/data
  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ../.env.example
    depends_on:
      - db
      - redis
  celery:
    build:
      context: ..
      dockerfile: docker/celery.Dockerfile
    env_file:
      - ../.env.example
    depends_on:
      - db
      - redis
volumes:
  db_data:
  redis_data: