services:
  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
    entrypoint: >
      sh -c "
      /app/scripts/wait-for.sh db:5432 &&
      python /app/src/manage.py wait_for_db &&
      python /app/src/manage.py migrate &&
      python /app/src/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ../src:/app/src
      - ../scripts:/app/scripts
      - web_uploads:/app/data/uploads
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://bibliflow:password@db:5432/bibliflow_dev
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=bibliflow.settings.dev
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - bibliflow_network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bibliflow_dev
      - POSTGRES_USER=bibliflow
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - bibliflow_network

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - bibliflow_network

  celery:
    build:
      context: ..
      dockerfile: docker/celery.Dockerfile
    entrypoint: >
      sh -c "
      /app/scripts/wait-for.sh db:5432 &&
      /app/scripts/wait-for.sh redis:6379 &&
      celery -A bibliflow worker --loglevel=info --concurrency=4
      "
    volumes:
      - ../src:/app/src
      - ../scripts:/app/scripts
      - web_uploads:/app/data/uploads
      - celery_processing:/app/data/processing
    environment:
      - DATABASE_URL=postgresql://bibliflow:password@db:5432/bibliflow_dev
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=bibliflow.settings.dev
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - bibliflow_network

volumes:
  postgres_data:
  redis_data:
  web_uploads:
  celery_processing:

networks:
  bibliflow_network:
    driver: bridge

